name = "noctua-osint-dashboard"
main = "functions/[[path]].py"
compatibility_date = "2024-01-01"

[env.production]
name = "noctua-osint-dashboard"
route = "intel.josebrevil.com/*"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.routes]]
pattern = "intel.josebrevil.com/*"
zone_name = "josebrevil.com" 